novuhq/docs

quickstarts/php.mdx
- Updated the command required to install the PHP SDK
- Fixed the screenshot displaying URL and not the image itself
=> Updated docs for PHP quickstart

quickstarts/nodejs.mdx
Fixed a typo where an undefined `notificationTemplateId` was referenced instead of the const `notificationWorkflowId`.
=> fix: typo `notificationTemplateId` -> `notificationWorkflowId`

mint.json
Currently users are getting a 404 when tring to go to /api/client-libraries as noted https://github.com/novuhq/novu/issues/4371
However by adding a simple redirect, the link will still work while we look to switch the reference.
=> Api docs Redirect

sdks/angular.mdx, sdks/dotnet.mdx, sdks/go.mdx, sdks/headless-javascript-service.mdx, sdks/iframe-embed.mdx, sdks/java.mdx, sdks/kotlin.mdx, sdks/laravel.mdx, sdks/nodejs.mdx, sdks/php.mdx, sdks/python.mdx, sdks/react.mdx, sdks/ruby.mdx, sdks/vue.mdx, sdks/web-component.mdx
This PR closes #154 by adding the icons to SDK Navigation bar create uniformity between UX across pages. The icons for ruby and kotlin wont be visible due to svg however i have added a icon space so that alignment with other headers are maintained.
=> Adding the missing icons to SDK Navigation Bar

channels-and-providers/email/mailtrap.mdx, mint.json
Documentation for Mailtrap email provider introduced in my PR https://github.com/novuhq/novu/pull/4328
Provider's links for reference:
- [Homepage](https://mailtrap.io/)
- [Get Started - Mailtrap Email Sending official docs](https://help.mailtrap.io/article/110-get-started-mailtrap-email-sending)
- [Sending Domain Setup official docs](https://help.mailtrap.io/article/69-sending-domain-setup)
=> Mailtrap docs

quickstarts/react.mdx, quickstarts/vue.mdx
1. notificaion -> notification 
2. varaibles -> variables
=> docs: fix typo in quickstarts/react.mdx

additional-resources/rate-limits.mdx
=> docs: fix typo in additional-resources/rate-limits.mdx

sdks/dotnet.mdx
=> Fixed issue highlighting the DOTNET/C# code snippet

mint.json, self-hosting-novu/introduction.mdx, self-hosting-novu/object-storage.mdx
This pr changes the s3 file to object store for self-hosting as we support s3, blob, and gcs in novu.
This had alot of questions as potential customers where thinking that we only support S3.
This PR should be rolled to Prod asap.
=> Change S3 to Object Store

api-reference/workflow-groups/create-workflow-group.mdx, api-reference/workflow-groups/delete-workflow-group.mdx, api-reference/workflow-groups/get-workflow-group.mdx, api-reference/workflow-groups/get-workflow-groups.mdx, api-reference/workflow-groups/update-workflow-group.mdx
closes #165 
added cURL request examples for:
- [Get workflow groups](https://docs.novu.co/api-reference/workflow-groups/get-workflow-groups)
- [Create workflow group](https://docs.novu.co/api-reference/workflow-groups/create-workflow-group)
- [Get workflow group](https://docs.novu.co/api-reference/workflow-groups/get-workflow-group)
- [Delete workflow group](https://docs.novu.co/api-reference/workflow-groups/delete-workflow-group)
- [Update workflow group](https://docs.novu.co/api-reference/workflow-groups/update-workflow-group)
=> feat: Added cURL Request Examples for Workflow Groups API in API Reference Documentation

_snippets/supported-channels.mdx, notification-center/client/angular.mdx, quickstarts/.NET.mdx, quickstarts/angular.mdx, quickstarts/go.mdx, quickstarts/iFrame.mdx, quickstarts/java.mdx, quickstarts/kotlin.mdx, quickstarts/nodejs.mdx, quickstarts/php.mdx, quickstarts/python.mdx, quickstarts/react.mdx, quickstarts/redwoodjs.mdx, quickstarts/ruby.mdx, quickstarts/vanillajs.mdx, quickstarts/vue.mdx
**Summary**
* Update Angular client and quickstart docs to specify support for version 15+, per https://github.com/novuhq/novu/pull/4518
* Formatting fixes on Angular quickstart
* Remove extra lines
* Add code-blocks for install CLI commands
* Adds a snippet for supported channels with some visual tidy-up
_Angular Client_
_Supported Channels Snippet_
=> docs(angular): Add support for Angular version 15+

api-reference/subscribers/get-subscriber.mdx
=> Added code for Node.js SDK

workflows/notification-workflows.mdx
Added a section that says that once a workflow is triggered, it can not be changed.
=> Resolved ticket DVRL-72

quickstarts/redwoodjs.mdx
Resolves #337
The redwood js mdx file will now successfully render in the browser :
Before:
After
=> Quickstart redwoodjs.mdx rendering successfully

additional-resources/data-migrations.mdx
Small fix to remove the trailing `.0` from `v0.9.0` and order versions chronologically.
=> fix(data-migrations): Fix ordering and typo

channels-and-providers/push/introduction.mdx, channels-and-providers/push/pushpad.mdx, mint.json
Pushpad provider has been added to Novu here: 
https://github.com/novuhq/novu/pull/4235
This pull requests adds the documentation for this provider.
=> Add Pushpad provider documentation

notification-center/client/vue.mdx
This is a follow-up from my previous MR https://github.com/novuhq/novu/pull/3964 to add a new `prop` to the vue notification center component.
I tried to follow the existing documentation for props by using a table to document the new prop.
=> docs: Update notification-center/vue props documentation

notification-center/client/react/api-reference.mdx
Add subscriber info in api-ref for headless.
Before: 
After:
=> fix: add subscriber info in api-ref (DVRL-2)

channels-and-providers/push/fcm.mdx
It'll fix the wrong import of `ChatProviderIdEnum` and import `PushProviderIdEnum` instead, as it should.
=> fix: wrong import of ChatProviderIdEnum

subscribers/topics.mdx
Fixes a typo (subscriebers) in the footer of the topics documentation.
Also adjusts headings to match how other areas of the documentation address topic actions:
"...to the topic" -> "...to a topic"
=> fix(docs) - fix typo on topics page

self-hosting-novu/aws.mdx, self-hosting-novu/azure.mdx, self-hosting-novu/deploy-with-docker.mdx, self-hosting-novu/gcp.mdx, self-hosting-novu/introduction.mdx, self-hosting-novu/terraform.mdx, use-cases/manage-notifications-in-multiple-languages.mdx, use-cases/send-notifications-at-any-scale.mdx
Started the (likely somewhat lengthy) process of updating calendly meetings to use Hubspot meetings instead.
I also updated several other outbound links to web.novu.co with new UTM parameters. We'll want to do that for all other Novu.co outbound links, too... eventually.
=> Meeting link replacement

quickstarts/go.mdx
The example was using `##` as a comment which is not valid in Go, replaced it with `//`
=> Fix Syntax Error in Code Snippet

inbox/headless/api-reference.mdx
I was a bit confused how to set the limit, but then noticed we spread the query in `httpClient.getFullResponse`, so we can pass limit from here.!
Adding `limit` to the examples
=> docs: update fetchNotifications to include limit

inbox/react/components.mdx, inbox/react/multiple-tabs.mdx
I’ve updated the Inbox documentation with instructions on how to use the `tabs` property.
=> chore: adjusted and clarified the use of the inbox tabs property

inbox/react/components.mdx, sdks/framework/typescript/steps/inbox.mdx
Updated the Inbox and Framework docs with the recent release of the `data` prop propagation and `redirect` urls.
https://github.com/user-attachments/assets/270aff12-ffd7-457d-9251-777604553d98
https://github.com/user-attachments/assets/bb06f853-e1b2-4874-b812-b2b9837e6aaa
=> chore: inbox and framework docs update for the notification data prop and redirect urls

api-reference/subscribers/get-in-app-notification-feed-for-a-particular-subscriber.mdx, workflow/delay.mdx
Added this usecase
> lets say workflow has 2 steps: delay 1 hour and then sms with skip if subscriber.data.isAllowed == false. Workflow was triggered and at that moment isAllowed for particular sub was false, but after 30 mins isAllowed was updated to true. When the workflow reaches sms, which isAllowed value it will use: update(true) or the one that was at the triggering moment(false)?
=> fix: add delay with in-app and skip

inbox/react/components/inbox.mdx, inbox/react/multiple-tabs.mdx
Inbox docs update:
- how to filter visible preferences
- updated the Tabs page with latest changes to `tabs` property
=> chore: inbox docs on how to filter preferences

sdks/framework/typescript/steps/introduction.mdx
**What?**
* Add documentation for `disableOutputSanitization` in Framework step options
_Example & documentation_
**Related PR:**
https://github.com/novuhq/novu/pull/6521
=> docs(framework): Add `disableOutputSanitization` for Framework step options

concepts/subscribers.mdx
* Clarify subscriber data handling instructions
The previous documentation was ambiguous with respect to fetching subscriber delivery data in realtime.
_Preview Deployment_
https://novu-clarify-subscriber-data-resolution.mintlify.app/concepts/subscribers#just-in-time
_New Content_
=> docs(subscribers): Clarify subscriber delivery data and metadata handling instructions

getting-started/introduction.mdx, inbox/react/migration-guide.mdx
1. Add missing icons on introduction page
2. Add information for @novu/react with @novu/framework compatibility
=> fix: add info for @novu/react compatibility with @novu/framework

quickstart/nuxt.mdx
Remove Remix references and replace them with Nuxt, adjusting the port from 4000 to 3000
=> docs(fix): Remove Remix references from nuxt.mdx

content/docs/platform/integrations/email/(providers)/mailersend.mdx, content/docs/platform/integrations/email/(providers)/sendgrid.mdx
- add info with explanation in which cases provider templates can be used using overrides
=> fix: add limitation info for using provider template in email channel

content/docs/platform/additional-resources/glossary.mdx
Reordered the list to follow an alphabetical order.
=> restructure glossary

content/docs/platform/inbox/react/headless.mdx
The previous documentation used a deprecated method for initializing the Novu SDK via `@novu/js`. This update corrects the code snippet and clarifies the recommended usage for developers using the Headless `<Inbox />` component.
The documentation previously showed:
```ts title="Deprecated"
import { Novu } from "@novu/js";
const novu = new Novu({
apiKey: 'YOUR_API_KEY',
});
However, this is no longer valid in the latest versions of the SDK, as the apiKey parameter is not recognized or used.
Solution:
import { Novu } from "@novu/js";
```ts title="Initialize Novu SDK (Correct Usage)"
export const novu = new Novu({
applicationIdentifier: 'YOUR_APPLICATION_IDENTIFIER',
subscriberId: 'YOUR_SUBSCRIBER_ID',
});
=> fix:Update `<Inbox />` Headless Tab Docs for `@novu/js` SDK Initialization

src/app/provider.tsx
This PR adds theming capabilities by integrating `ThemeProvider` from `next-themes`:
- Imported `ThemeProvider` in `src/app/provider.tsx`.  
- Wrapped the application children in `<ThemeProvider attribute="class" defaultTheme="system" enableSystem>`.  
- Removed hardcoded `defaultTheme` config in `RootProvider` to delegate theme control to `next-themes`.  
- Verified light/dark mode toggles on system theme change and user override.  
- Confirmed CSS class switching on `<html>` element.
=> feat: integrate ThemeProvider for improved theming support

content/docs/platform/concepts/subscribers.mdx
This PR adds a dedicated concept page for Subscribers, explaining their role within Novu's notification system. It introduces subscribers as the foundational entity for targeting notifications and managing preferences, and clarifies how they interact with workflows, channels, and topics.
What's included:
- Definition of a subscriber in Novu
- Overview of subscriber identifiers and profile structure
- Subscriber creation in Novu
- Explanation of preference management and environment scoping
=> Update the subscribers content

content/docs/community/self-hosting-novu/deploy-with-docker.mdx
- Changed the dashboard access URLs from port 4200 to 4000 for both local and VPS deployments.
- Updated related commands to reflect the new port for consistency across the documentation.
=> docs: update local and VPS dashboard URLs in self-hosting documentation

content/docs/platform/meta.json
The PR is to fix the manage members page position on the account section sidebar.
=> Fix manage members page to appear on the section
