- overview/introduction.mdx
https://github.com/novuhq/docs/assets/63902456/4a63173d-edfa-44f8-a9e9-1bba4743ed90
> Have changed & enhanced the section of "notification vs. messages" definitions

- api-reference/execution-details/get-execution-details.mdx
- api-reference/inbound-parse/validate-the-mx-record-setup-for-the-inbound-parse-functionality.mdx
- api-reference/integrations/set-integration-as-primary.mdx
- api-reference/workflow-groups/create-workflow-group.mdx
- api-reference/workflow-groups/delete-workflow-group.mdx
- api-reference/workflow-groups/get-workflow-group.mdx
- api-reference/workflow-groups/get-workflow-groups.mdx
- api-reference/workflow-groups/update-workflow-group.mdx
- api-reference/workflows/create-workflow.mdx
- api-reference/workflows/delete-workflow.mdx
- api-reference/workflows/get-workflow.mdx
- api-reference/workflows/get-workflows.mdx
- api-reference/workflows/update-workflow-status.mdx
- api-reference/workflows/update-workflow.mdx
- faqs/questions.mdx
Add pending methods and added one FAQ
> api-ref: pending methods

- mint.json
* 1 less click to retrieve API key
> feat(cta): Retrieve API Key faster

- community/run-in-local-machine.mdx
> fix: flicker on tab change

- notification-center/client/headless/api-reference.mdx
Add docs for markNotificationsAs
PR: https://github.com/novuhq/novu/pull/4228
> docs: Add docs for markNotificationsAs

- quickstarts/.NET.mdx
- quickstarts/angular.mdx
- quickstarts/go.mdx
- quickstarts/iFrame.mdx
- quickstarts/java.mdx
- quickstarts/react.mdx
- quickstarts/vanillajs.mdx
- quickstarts/vue.mdx
adding all available font icons, custom icons through svg not possible for rest
> chore: add icons to quickstarts

- api-reference/workflows/create-workflow.mdx
- api-reference/workflows/delete-workflow.mdx
- api-reference/workflows/get-workflow.mdx
- api-reference/workflows/get-workflows.mdx
- api-reference/workflows/update-workflow-status.mdx
- api-reference/workflows/update-workflow.mdx
Resolved Issue #164 
@unicodeveloper  @davidsoderberg @LetItRock
> feat: added curl req example for workflow api

- faqs/questions.mdx
I have changed the wrong redirect url to correct one as I mentioned on this issue #176
> fix-wrongredirecturl

- quickstarts/go.mdx
closes https://github.com/novuhq/go-novu/issues/59
part of https://github.com/novuhq/go-novu/pull/62
> add exponential retry docs for golang

- quickstarts/01-introduction.mdx
- sdks/dotnet.mdx
I have changed the wrong redirect url to correct one as i mentioned on this issue #181
> fix - .net quickstart wrong url

- mint.json
I have changed the wrong linkedin handle to correct one. 
Solved issue #190
> fix-linkedin-handle

- channels-and-providers/chat/mattermost.mdx
issue #108 
What other changes can I make to this documentation? @unicodeveloper
> mattermost chat provider documentation

- channels-and-providers/sms/46elks.mdx
Fixes #115 
Added 46elks SMS provider doc.
> Add 46elks doc

- notification-center/client/angular.mdx
- quickstarts/angular.mdx
This PR addresses an issue where the Angular version mentioned in the project's documentation is incorrect. I have updated the documentation to reflect the accurate Angular version.
> fix: fix angular version

- demos/introduction.mdx
This PR closes #146 by adding cards and improving the UX of the Demos Page.
> Update UX of the Demos Page

- api-reference/events/broadcast-event-to-all.mdx
- api-reference/events/bulk-trigger-event.mdx
- api-reference/events/cancel-triggered-event.mdx
- api-reference/events/trigger-event.mdx
I have added the cURL examples for Events in API Reference Documentation.  #163 
Also all cURL commands are tested by me on my own account.
> Add Curl Request Examples for Events API in API Reference Documentation #163

- api-reference/events/cancel-triggered-event.mdx
> Updated the doc for cancel triggered event

- workflows/step-filters.mdx
I have changed the wrong URL of **subscribers attributes** with right one as i mentioned on this issue #208
> Fix the wrong url of sub sttribute

- api-reference/feeds/create-feed.mdx
> fix: wrong documentation of the response of `Create Feed` endpoint

- channels-and-providers/sms/kannel.mdx
Added Kannel sms provider documentation as per issue #116
> Add Kannel sms provider documentation

- channels-and-providers/sms/sms-central.mdx
Solves #118 
Added SMS Central startup guide documentation.
> Add sms-central doc

- demos/introduction.mdx
I have solved the parsing issue in demo section of the apps and wrong redirect wrong problem as i mentioned on it #222
> fix the parsing problem and wrong redirect url

- subscribers/topics.mdx
> docs: fix typos in quickstarts/vue.mdx

- channels-and-providers/in-app/introduction.mdx
> docs: fix typo in channels-and-providers/in-app/introduction.mdx

- quickstarts/vue.mdx
> docs: fix typo in quickstarts/vue.mdx

- notification-center/client/react/get-started.mdx
> docs: fix typo in notification-center/client/react/getting-started.mdx

- community/machine-setup.mdx
Updates pnpm version connected to: https://github.com/novuhq/novu/pull/4528
> docs: update pnpm version

- quickstarts/kotlin.mdx
- quickstarts/nextjs.mdx
- quickstarts/redwoodjs.mdx
- quickstarts/ruby.mdx
- self-hosting-novu/kubernetes.mdx
> sidebar icons fixed

- getting-started/send-your-first-notification.mdx
| Before      | After |
| ----------- | ----------- |
| ![image](https://github.com/novuhq/docs/assets/43641536/f68b0818-23f2-4baa-8408-78b33ba0d6b8)| ![image](https://github.com/novuhq/docs/assets/43641536/d446f836-a1e8-4634-a318-846b3343cd7f) |
Page
https://docs.novu.co/getting-started/send-your-first-notification
> Added space between Frame and Warning

- community/machine-setup.mdx
- quickstarts/python.mdx
Fixed : #247
| Before      | After |
| ----------- | ----------- |
| ![image](https://github.com/novuhq/docs/assets/43641536/8f0c09f4-a5cf-453b-a6a3-60e44467547c) | ![image](https://github.com/novuhq/docs/assets/43641536/c2fda5fe-7e57-4b52-9904-b870f10554fd) |
https://docs.novu.co/community/machine-setup
https://docs.novu.co/quickstarts/python
> Changed markdown image tag to frame tag (#247)

- getting-started/send-your-first-notification.mdx
| Before      | After |
| ----------- | ----------- |
| ![image](https://github.com/novuhq/docs/assets/43641536/b68235da-ebdf-465a-915d-c29a8fe48c7a) | ![image](https://github.com/novuhq/docs/assets/43641536/a24b84b0-40bb-4ee5-83cb-6774a1ea0649) |
| ![image](https://github.com/novuhq/docs/assets/43641536/80504800-c85d-4732-913a-57af271dc53a) | ![image](https://github.com/novuhq/docs/assets/43641536/f1623e1a-e733-4fde-9855-593f4065333a) |
| ![image](https://github.com/novuhq/docs/assets/43641536/ec3e7040-2a28-48fc-af4c-7b790c38c3f8) | ![image](https://github.com/novuhq/docs/assets/43641536/18faa871-95c9-40ea-870a-8ce686ab3cf3) |
| ![image](https://github.com/novuhq/docs/assets/43641536/394fd31c-bc9a-4e82-8bd0-7d90266f28ea) | ![image](https://github.com/novuhq/docs/assets/43641536/de238646-8 …
> Fixed spacing between element

- quickstarts/angular.mdx
This PR fixes #255 
I have formatted the document, here is one example:
Before:
After:
The caption on the iframe was not visible, I resolved this issue too.
> chore: formatted the document at path /quickstarts/angular.mdx

- api-reference/environments/get-api-keys.mdx
- api-reference/environments/regenerate-api-keys.mdx
> feat: Added Python environments `get api keys` and `regenerate api keys` example

- channels-and-providers/sms/burst-sms.mdx
issue [#113](https://github.com/novuhq/docs/issues/113)
BurstSMS docs added.
> BurstSMS docs added

- channels-and-providers/sms/africas-talking.mdx
- channels-and-providers/sms/aws-sns.mdx
- channels-and-providers/sms/burst-sms.mdx
- channels-and-providers/sms/clickatell.mdx
- channels-and-providers/sms/firetext.mdx
- channels-and-providers/sms/gupshup.mdx
- channels-and-providers/sms/infobip.mdx
- channels-and-providers/sms/nexmo.mdx
- channels-and-providers/sms/plivo.mdx
- channels-and-providers/sms/sendchamp.mdx
- channels-and-providers/sms/sms77.mdx
- channels-and-providers/sms/telnyx.mdx
- channels-and-providers/sms/termii.mdx
- channels-and-providers/sms/twilio.mdx
> Update sms-providers doc

- api-reference/notification/get-notification-graph-statistics.mdx
- api-reference/notification/get-notification-statistics.mdx
- api-reference/notification/get-notification.mdx
- api-reference/notification/get-notifications.mdx
> feat: Added Python NotificationApi Examples

- README.md
I have changed the name of Twitter to X in the README file of this repo.
Everyone must be well aware by now that the legal name of Twitter has been formally changed to X. Therefore, I have updated the README files and corrected the name to X. Wouldn't it be best to be updated with the latest?
Kindly review the PR and merge it. Suggest changes (if any)
Closes Issue #299
> Updated the name of Twitter to X

- channels-and-providers/sms/clicksend.mdx
Added clicksend docs for novu integration.
Solves issue #287
> Add clicksend docs

- api-reference/feeds/create-feed.mdx
- api-reference/feeds/delete-feed.mdx
- api-reference/feeds/get-feeds.mdx
> feat: added cURL Request Examples for FeedApi

- community/add-a-new-provider.mdx
Space has been added to docs-feedback. Closes https://github.com/novuhq/docs/issues/307
> Added space in docs-feedback 

- additional-resources/idempotency.mdx
- mint.json
for https://github.com/novuhq/novu/issues/4469
> add idempotency docs

- api-reference/subscribers/create-subscriber.mdx
> Fixed JS code for Create subscriber

- channels-and-providers/push/pusher-beams.mdx
- mint.json
Add Pusher Beam Push Provider Documentation
Closes #292
> docs(pusher-beams): add pusher beams doc

- channels-and-providers/sms/sns.mdx
Added SNS provider documentation for integration with novu.
Fixes #318
> Add SNS provider documentation

- channels-and-providers/email/amazonses.mdx
- channels-and-providers/email/custom-smtp.mdx
- channels-and-providers/email/infobip.mdx
- channels-and-providers/email/mailersend.mdx
- channels-and-providers/email/mailgun.mdx
- channels-and-providers/email/mailjet.mdx
- channels-and-providers/email/mailtrap.mdx
- channels-and-providers/email/mandrill.mdx
- channels-and-providers/email/netcore.mdx
- channels-and-providers/email/outlook365.mdx
- channels-and-providers/email/plunk.mdx
- channels-and-providers/email/postmark.mdx
- channels-and-providers/email/resend.mdx
- channels-and-providers/email/sendgrid.mdx
- channels-and-providers/email/sendinblue.mdx
- channels-and-providers/email/sparkpost.mdx
Updated the email providers documentation.
Solves #321
> Update Email providers docs

- community/windows-machine-setup.mdx
fixed the inconsistency and typo error on the windows docs#303
> fixed inconsistency and typo in windows docs

- api-reference/notification/get-notification-graph-statistics.mdx
- api-reference/notification/get-notification-statistics.mdx
- api-reference/notification/get-notification.mdx
- api-reference/notification/get-notifications.mdx
> feat: Added cURL Request Examples for NotificationApi in API Reference Documentation

- mint.json
@unicodeveloper have a look! 🙏
> fix: add slack and discord guides to navigation

- content-creation-design/handlebars-helpers.mdx
> New Info: Added docs for `pluralize` handlebar helper (Resolve ticket DVRL-28)

- content-creation-design/handlebars-helpers.mdx
> New Info: Usecase added to resolve ticket DVRL-65

- quickstarts/python.mdx
> Quickstart python.mdx rendering successfully

- additional-resources/data-migrations.mdx
- additional-resources/glossary.mdx
- additional-resources/idempotency.mdx
- additional-resources/rate-limits.mdx
- mint.json
- self-hosting-novu/object-storage.mdx
**What does this PR do?**
* Add data migration documentation
* Add missing icons to all top-level pages for consistency and faster page identification
**Why is this PR needed?**
Novu Self-hosted users are required to run the migrations on their own databases to support new feature releases. By listing all migrations alongside the relevant version in a single place, self-hosted users can more easily self-serve the relevant migrations they need to run when performing version upgrades.
_NB: The "Migrations History" section must be updated whenever a new migration is introduced in a release version. We should add this to our release playbook._
_Data Migrations Page_
_Sidebar with all top-level icons_
> feat: Add database migration docs & all top-level page icons

- mint.json
- workflows/notification-workflows.mdx
Added 0.20.0 & 0.21.0 versions to the docs dropdown option.
> feat: Added 0.20 & 0.21 versions to dropdown.

- subscribers/preferences.mdx
> new info: Added info about  "Global level channel preferences" (Ticket DVRL-39)

- quickstarts/go.mdx
Resolves #345
Made updations in the mdx file for golang quickstarts 
Before the mdx file was not rendering now it is , this PR makes the file to be successfully rendered in the browser
> Updated the mdx file to be able to rendered

- workflows/notification-workflows.mdx
This PR adds a new subsection titled "Execution of Workflow Steps" under our documentation's "Structure" section. 
It explains how steps are executed within a workflow, emphasizing sequential execution, the importance of channel order, and how it contributes to consistency and reliability in the notification process. 
This addition enhances our documentation by providing users with valuable insights into the workflow execution process.
> Add documentation on the execution of workflow channels [DVRL-61]

- subscribers/topics.mdx
> new info: Clarification about "topic" creation [Ticket DVRL-60]

- workflows/notification-workflows.mdx
> Added error fix as FAQs section to the workflow page [Ticket DVRL-31]

- architecture/diagrams.mdx
- architecture/introduction.mdx
- getting-started/commercial-open-source.mdx
- mint.json
Adds the initial architecture overview for Novu
> Add Inital Novu Architecture tab

- quickstarts/redwoodjs.mdx
- quickstarts/vue.mdx
Hi
Please find some changes to resolve the inconsistency of heading sizes for some of the documents ( Vue, RedwoodJS).
Issue #301
Issue link: https://github.com/novuhq/docs/issues/301
Thanks
> Docs: Inconsistent size of headings #301 Resolved

- api-reference/events/trigger-event.mdx
- api-reference/subscribers/get-subscribers.mdx
Just a couple super minor updates that didn't make it in the previous PR: https://github.com/novuhq/docs/pull/319
> Minor Fix for a Couple Subscriber Java Examples

- quickstarts/.NET.mdx
- quickstarts/angular.mdx
- quickstarts/go.mdx
- quickstarts/java.mdx
- quickstarts/kotlin.mdx
- quickstarts/nextjs.mdx
- quickstarts/nodejs.mdx
- quickstarts/php.mdx
- quickstarts/python.mdx
- quickstarts/redwoodjs.mdx
- quickstarts/ruby.mdx
- quickstarts/vue.mdx
#301 Suggestion / Fix
Changed heading size. Framework name h1. Following headings h2. 
I used Quickstart/Client-Side/React as a template
> Adjusted heading size to look uniform

- subscribers/preferences.mdx
- workflows/notification-workflows.mdx
> docs: Add instructions for disabling a workflow for a single subscriber [ticket DVRL-22]

- faqs/questions.mdx
- subscribers/subscribers.mdx
> Added new info about subscribers based on FAQ [Ticket DVRL-67]

- content-creation-design/handlebars-helpers.mdx
> Added `numberFormat` helper info [Ticket DVRL-98]

- api-reference/messages/delete-message-by-transactionid.mdx
- mint.json
- openapi.json
I have introduced a new API endpoint at /v1/messages/transaction/{transactionId} in the API reference.
As I'm currently unable to conduct local testing and need to await a response from the Mintlify team regarding a particular issue, I have marked this Pull Request as a 'Draft' for the time being.
> docs: added delete-message-by-transactionid api ref [DVRL-53]

- self-hosting-novu/introduction.mdx
@unicodeveloper please review
Before: 
<br />
After:
> docs: add self-host login info (DVRL-122)

- api-reference/notification/get-notification-graph-statistics.mdx
- api-reference/notification/get-notification-statistics.mdx
- api-reference/notification/get-notification.mdx
- api-reference/notification/get-notifications.mdx
> feat: Added PHP Request Examples for NotificationApi in API Reference Documentation

- getting-started/how-novu-works.mdx
- "How Novu works" is a relative clause.
- "How does Novu work?" is a question.
- "How Novu works?" is neither.
For an example of a relative clause, consider the sentence: "If you have a few mintues, I can show you how Novu works."
> Update how-novu-works.mdx to improve grammar of title

- api-reference/subscribers/get-subscribers.mdx
- notification-center/client/headless/get-started.mdx
- notification-center/client/react/get-started.mdx
1. Add nodejs subscriber list method
2. Add a CORS error FAQ in react and headless NC
> feat: add subscriber list nodejs method and NC FAQ

- guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> Revert "Update how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-N…"

- channels-and-providers/email/sendinblue.mdx
> feat: add sendinblue email templates section

- community/add-a-new-provider.mdx
- community/run-in-local-machine.mdx
> fix: change old node version to 20.8.1

- community/windows-machine-setup.mdx
> fix: window local machine docs

- api-reference/environments/get-api-keys.mdx
- api-reference/environments/get-current-environment.mdx
- api-reference/environments/get-environments.mdx
- api-reference/environments/regenerate-api-keys.mdx
Hi @jainpawan21 please check this PR.
Closed: #265
> Added cURL environments examples (#265)

- community/code-of-conduct.mdx
- community/get-involved.mdx
- community/introduction.mdx
- mint.json
> Community 2.0

- workflows/digest.mdx
> Workflows - Digest: Remove repeated section

- channels-and-providers/push/expo-push.mdx
ChatProviderIdEnum was wrongly imported in place of PushProviderIdEnum
> Fix wrong import in. Update expo-push.mdx.

- echo/sdk/frameworks/nextjs.mdx
**What?**
* Add Echo API framework docs for Next.js pages router
**Why?**
Next.js Pages router is supported, we need documentation for it.
**Screen**
> feat(echo): Next.js pages router framework docs

- echo/concepts/workflows.mdx
**What?**
pull in defaults
**Why?**
Defaults make it easier to copy the snippet and get started quickly
> fix(echo): Add defaults to workflow example

- echo-terminal.js
- echo/quickstart.mdx
- snippets/echo-terminal.mdx
**What?**
* Add echo code snippet
**Why?**
* Mintlify have exposed more logs via Dashboard and CLI, we need to understand the reason for deployment failure
Code snippet terminal successfully loading on the Mintlify branch preview deploy:
https://novu-preview-echo-snippet-with-logs.mintlify.app/echo/quickstart
> feat(echo): Add code snippet

- echo-terminal.js
- snippets/echo-terminal.mdx
**What?**
* Load the echo code snippet on the snippet to load on page change
> fix(echo): Load snippet on page change

- echo/steps/chat.mdx
- echo/steps/custom.mdx
- echo/steps/delay.mdx
- echo/steps/digest.mdx
- echo/steps/email.mdx
- echo/steps/in-app.mdx
- echo/steps/introduction.mdx
- echo/steps/push.mdx
- echo/steps/sms.mdx
- mint.json
- Refactored steps to be it's own section in docs
- Introduced a new step type
> feat: custom step type

- echo/sdk/frameworks/h3.mdx
- echo/sdk/frameworks/remix.mdx
- echo/sdk/frameworks/sveltekit.mdx
- mint.json
_Navbar_
_Remix_
_Sveltekit_
_H3_
> feat(echo): Add Remix, Sveltekit, and H3 docs

- self-hosting-novu/deploy-with-docker.mdx
- [Follow this slack conversation](https://novu.slack.com/archives/C06NABQRFQU/p1718215278398389?thread_ts=1718171032.420369&cid=C06NABQRFQU)
> fix: update docker community directory info for self hosting

- echo-terminal.js
Update animated code terminal to show new code paradigm
> chore: update docs

- concepts/controls.mdx
- concepts/endpoint.mdx
- concepts/workflows.mdx
- deployment/actions.mdx
1. Add workflow trigger identifier information 
2. Few fixes
> fix: add workflow trigger identifier

- inbox/introduction.mdx
> chore: fix typos

- account/authentication.mdx
- enterprise/authentication.mdx
- mint.json
> chore: add authentication documentation

- sdks/framework/typescript/steps/chat.mdx
- sdks/framework/typescript/steps/custom.mdx
- sdks/framework/typescript/steps/delay.mdx
- sdks/framework/typescript/steps/digest.mdx
- sdks/framework/typescript/steps/email.mdx
- sdks/framework/typescript/steps/inbox.mdx
- sdks/framework/typescript/steps/introduction.mdx
- sdks/framework/typescript/steps/push.mdx
- sdks/framework/typescript/steps/sms.mdx
- sdks/framework/typescript/workflow.mdx
- sdks/kotlin.mdx
- sdks/laravel.mdx
- sdks/ruby.mdx
**What?**
* Add `tags` parameter to Workflow Options documentation
**Screenshot**
> docs: Add `tags` parameter to Workflow Options documentation

- sdks/framework/typescript/steps/chat.mdx
- sdks/framework/typescript/steps/custom.mdx
- sdks/framework/typescript/steps/delay.mdx
- sdks/framework/typescript/steps/digest.mdx
- sdks/framework/typescript/steps/email.mdx
- sdks/framework/typescript/steps/inbox.mdx
- sdks/framework/typescript/steps/introduction.mdx
- sdks/framework/typescript/steps/push.mdx
- sdks/framework/typescript/steps/sms.mdx
- sdks/framework/typescript/workflow.mdx
- sdks/kotlin.mdx
- sdks/laravel.mdx
- sdks/ruby.mdx
> Revert "docs: Add `tags` parameter to Workflow Options documentation"

- inbox/react/multiple-tabs.mdx
- updated the docs to use tabs instead of tags
> fix: tags -> tabs

- api-reference/organizations/create-organization.mdx
- api-reference/organizations/delete-member-from-organization.mdx
- api-reference/organizations/get-all-members-of-current-organization.mdx
- api-reference/organizations/get-all-organizations.mdx
- api-reference/organizations/get-current-organization.mdx
- api-reference/organizations/rename-organization.mdx
- api-reference/organizations/update-member-role-to-admin.mdx
- api-reference/organizations/update-organization-branding.mdx
- content-creation-design/translations.mdx
- snippets/self-host-only-api.mdx
Added self host only snippet file
Used that snippet file in all organizations apis
https://github.com/user-attachments/assets/9b565447-702d-4490-a002-65bb77b0538b
> fix: add self host only snippet for organizations api

- help/account-management.mdx
Free trial duration is going to be changed to 14 days
> feat(billing): update free trial duration

- inbox/react/customization.mdx
- Added more examples for appearance usage
> feat: examples

- inbox/react/styling.mdx
> chore: inbox render subject or body text in bold

- integrations/providers/sms/overview.mdx
Updated the formatting for the codeblock from
```
import { Novu } from '@novu/node';
const novu = new Novu('<NOVU_SECRET_KEY>');
novu.trigger('<WORKFLOW_TRIGGER_IDENTIFIER>', {
to: {
subscriberId: '<SUBSCRIBER_ID>',
},
overrides: {
sms: {
integrationIdentifier: "infobip-abcdef"
},
},
});
```
to
```
import { Novu } from '@novu/node';
const novu = new Novu('<NOVU_SECRET_KEY>');
novu.trigger('<WORKFLOW_TRIGGER_IDENTIFIER>', {
to: {
subscriberId: '<SUBSCRIBER_ID>',
},
overrides: {
sms: {
integrationIdentifier: 'infobip-abcdef',
},
},
});
```
> chore: apply formatting in overview.mdx

- inbox/headless/api-reference.mdx
- inbox/react/hooks/novu-provider.mdx
- inbox/react/hooks/overview.mdx
- inbox/react/hooks/use-counts.mdx
- inbox/react/hooks/use-notifications.mdx
- inbox/react/hooks/use-novu.mdx
- inbox/react/hooks/use-preferences.mdx
- mint.json
- snippets/inbox/headless/api-reference/novu-params.mdx
- snippets/inbox/react/novu-provider-example.mdx
- snippets/inbox/react/use-notifications-example.mdx
- snippets/inbox/react/use-unread-count-example.mdx
The React Hooks API reference.
https://github.com/user-attachments/assets/98083eff-702a-40fa-bb81-6d8e60afdfae
https://github.com/user-attachments/assets/c0cfa306-57f2-4ceb-9186-a851bddda65a
https://github.com/user-attachments/assets/896fd5d4-0d0b-44f4-b38f-dcd87c57e939
https://github.com/user-attachments/assets/d9ee80b4-dfd9-4e7d-810a-096dbc7c9907
https://github.com/user-attachments/assets/57995e16-1803-4a12-a72a-4f71e50ec2da
https://github.com/user-attachments/assets/e6c0996f-7ead-49af-a259-905154b0da76
> feat: inbox react hooks api reference

- inbox/react/styling.mdx
> feat: add color-shadow

- community/self-hosting-novu/deploy-with-docker.mdx
- community/self-hosting-novu/introduction.mdx
- community/self-hosting-novu/telemetry.mdx
- mint.json
This PR fixes INF-436. 
This includes docs needed for community deployment. Refer to the screenshot 
This PR depends on novuhq/novu#6625
> docs(community): improve documentation for v2 community release

- getting-started/how-novu-works.mdx
- quickstart/overview.mdx
Added some context to the main quickstart landing page
> Quickstart LP updates

- workflow/studio.mdx
**What?**
* Add headless `npx novu dev` CLI docs
Implementation PR: https://github.com/novuhq/novu/pull/7016
> feat(framework): Add headless `npx novu dev` CLI docs

- inbox/react/localization.mdx
> Updating new localization key mapping

- recipes/workflows/translations.mdx
- fixed use of `getFixedT` method
- fixed the use of subscriber variables
> fix: translations recipe example code

- framework/controls.mdx
Adding Documentation for Pull Request to add Class-Validator support:
https://github.com/novuhq/novu/pull/6945
>  feat(framework): add class-validator support - Update controls.mdx

- content/docs/platform/inbox/react/hooks.mdx
https://github.com/user-attachments/assets/8c620469-3028-4f25-a75f-7d9398608eca
> chore: inbox hooks page improvements

- content/docs/framework/custom.mdx
- content/docs/framework/delay.mdx
- content/docs/framework/meta.json
- content/docs/framework/skip.mdx
- adds separate step function page so that it can be discovered easily
> feat: add step function page

- content/docs/platform/concepts/subscribers.mdx
- update subscribers page missing content
- add subscribers page dashboard gif
> fix: update subscribers page content

- .github/workflows/pr-checks.yml
- pnpm-lock.yaml
> fix: pnpm lock file duplicate entry

- content/docs/platform/meta.json
- content/docs/platform/what-is-novu.mdx
- src/middleware.ts
Updated the previous content for the "What is Novu" page for the new one.
Created a new path to (https://docs-novu.netlify.app/platform/what-is-novu) and redirected the old path (https://docs-novu.netlify.app/platform/how-novu-works) to the new one.
> Updated the content for the "What is Novu" page and handled redirects

- content/docs/platform/concepts/workflows.mdx
Adds the "Workflow" core concept page to the documentation. This page explains workflows as the central orchestration layer in Novu, describing their structure, execution, and configuration.
* Defines what a workflow is and how it functions within Novu’s architecture.
* Covers the Workflow Editor, notification templates, step types, and filters.
* Documents triggering mechanics (including payloads, subscribers, and job lifecycle).
* Explains workflow status, tags, and identifiers.
* Includes advanced features like subscriber preferences, critical workflows, and conditional logic.
Provides a complete conceptual foundation for understanding and using workflows in Novu.
> Update content for workflows core concept page

- content/docs/framework/delay.mdx
- content/docs/framework/digest.mdx
- content/docs/framework/typescript/steps/digest.mdx
- content/docs/platform/workflow/delay.mdx
- content/docs/platform/workflow/digest.mdx
- add digest and delay failure faq
- add cron and custom digest key in types and example
> fix: add digest cron and custom digest key

- content/docs/platform/sdks/server/laravel.mdx
Simple PR to fix the incorrect repo link :)
> Fix Laravel SDK repo link

- content/docs/community/add-a-new-provider.mdx
- content/docs/community/meta.json
- src/middleware.ts
1. update create a new provider doc 
2. added in meta.json file
3. removed redirect from middleware
⚠️ Merge this PR after https://github.com/novuhq/novu/pull/8329
> fix: update add a new provider guide as per new changes

- content/docs/framework/schema/class-validator.mdx
- content/docs/framework/schema/json-schema.mdx
- content/docs/framework/schema/meta.json
- content/docs/framework/schema/zod.mdx
PR Ref: https://github.com/novuhq/docs/pull/771
> feat: add class validator support framework

- content/docs/platform/integrations/email/activity-tracking/index.mdx
@jainpawan21 Kindly approve and merge this as soon as possible
> Fix wrong text and link in the activity tracking page
